language: node_js
sudo: false
node_js:
- '12'
os:
- linux
script:
- npm test
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  on:
    tags: true
    branch: master
    repo: RHElements/lgtm
